server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations/ # Folder on the classpath for configuration files


management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: INFO
    com.your.package: DEBUG
